language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env:
        - TEST_COVERAGE=true
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm

install:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev satooshi/php-coveralls ; fi

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $TEST_COVERAGE != 'true' ]]; then ./vendor/bin/phpunit ; fi

